# Generated by Django 6.0.2 on 2026-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Например: МГУ им. Ломоносова, НИИ Ядерной физики, Школа №123 и т.д.', max_length=255, verbose_name='Место работы/учебы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Выберите тематики, которые вас интересуют', to='conferences.topic', verbose_name='Научные интересы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('', 'Нет степени'), ('student', 'Студент'), ('phd_student', 'Аспирант'), ('phd', 'Кандидат наук'), ('dsc', 'Доктор наук'), ('prof', 'Профессор'), ('assoc_prof', 'Доцент'), ('teacher', 'Преподаватель'), ('researcher', 'Научный сотрудник'), ('other', 'Другое')], help_text='Выберите ваш статус/степень', max_length=100, verbose_name='Ученая степень'),
        ),
    ]
