# Generated by Django 6.0.2 on 2026-02-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полное официальное название', max_length=300, verbose_name='Название конференции')),
                ('short_title', models.CharField(blank=True, help_text='Аббревиатура или краткая форма (например: "ICM-2024")', max_length=100, verbose_name='Краткое название')),
                ('slug', models.SlugField(blank=True, help_text='Будет создан автоматически из названия', unique=True, verbose_name='URL-идентификатор')),
                ('conference_type', models.CharField(choices=[('international', 'Международная'), ('national', 'Всероссийская'), ('regional', 'Региональная'), ('university', 'Вузовская'), ('school', 'Школа-конференция'), ('symposium', 'Симпозиум'), ('congress', 'Конгресс')], default='international', max_length=20, verbose_name='Тип конференции')),
                ('format', models.CharField(choices=[('offline', 'Очная (офлайн)'), ('online', 'Онлайн'), ('hybrid', 'Гибридная (очно + онлайн)')], default='offline', max_length=20, verbose_name='Формат проведения')),
                ('access_level', models.CharField(choices=[('public', 'Открытая для всех'), ('registered', 'Только для зарегистрированных'), ('invite', 'По приглашениям')], default='public', max_length=20, verbose_name='Уровень доступа')),
                ('start_date', models.DateField(help_text='Дата начала конференции', verbose_name='Дата начала')),
                ('end_date', models.DateField(help_text='Дата окончания конференции', verbose_name='Дата окончания')),
                ('deadline', models.DateField(help_text='Последний день подачи заявок/тезисов', verbose_name='Дедлайн подачи заявок')),
                ('location', models.CharField(blank=True, help_text='Город, место проведения (для онлайн - укажите "Онлайн")', max_length=255, verbose_name='Место проведения')),
                ('venue', models.CharField(blank=True, help_text='Конкретное место: название вуза, конференц-зала и т.д.', max_length=255, verbose_name='Площадка проведения')),
                ('address', models.TextField(blank=True, help_text='Полный адрес с индексом', verbose_name='Адрес проведения')),
                ('online_platform', models.CharField(blank=True, help_text='Например: Zoom, Webinar, Свой сервис', max_length=200, verbose_name='Платформа для онлайн-участия')),
                ('description', models.TextField(help_text='Подробное описание, цели, задачи', verbose_name='Описание конференции')),
                ('program', models.TextField(blank=True, help_text='Программа мероприятия, пленарные докладчики', verbose_name='Программа конференции')),
                ('requirements', models.TextField(blank=True, help_text='Требования к тезисам, статьям, презентациям', verbose_name='Требования к оформлению')),
                ('participation_terms', models.TextField(blank=True, help_text='Организационный взнос, проживание, трансфер', verbose_name='Условия участия')),
                ('contact_email', models.EmailField(help_text='Email оргкомитета для вопросов', max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_person', models.CharField(blank=True, help_text='К кому обращаться по вопросам', max_length=200, verbose_name='Контактное лицо')),
                ('website', models.URLField(blank=True, help_text='Официальный сайт, если есть отдельный', verbose_name='Сайт конференции')),
                ('call_for_papers', models.URLField(blank=True, help_text='Ссылка на форму подачи заявок', verbose_name='Ссылка на сборник тезисов')),
                ('poster', models.ImageField(blank=True, help_text='Изображение для привлечения внимания', null=True, upload_to='conferences/posters/', verbose_name='Постер конференции')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной в блоке "Рекомендуемые"', verbose_name='Рекомендуемая')),
                ('is_free', models.BooleanField(default=True, help_text='Участие бесплатное?', verbose_name='Бесплатная')),
                ('has_publications', models.BooleanField(default=True, help_text='Планируется ли публикация сборника трудов?', verbose_name='Публикация материалов')),
                ('publication_indexing', models.CharField(blank=True, help_text='Например: РИНЦ, Scopus, WoS', max_length=200, verbose_name='Индексация публикаций')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликована'), ('rejected', 'Отклонена'), ('archived', 'В архиве'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('favorites_count', models.PositiveIntegerField(default=0, editable=False, help_text='Сколько пользователей добавили в избранное', verbose_name='В избранном')),
                ('applications_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Заявок подано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('organization', models.ForeignKey(help_text='Организация, проводящая конференцию', on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='organizations.organization', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='conferences/files/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('info_letter', 'Информационное письмо'), ('program', 'Программа'), ('rules', 'Правила оформления'), ('presentation', 'Презентация'), ('other', 'Другое')], default='info_letter', max_length=50, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Файл конференции',
                'verbose_name_plural': 'Файлы конференции',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название тематики')),
                ('slug', models.SlugField(blank=True, help_text='Будет создан автоматически из названия', unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, help_text='Краткое описание тематики', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли в фильтрах', verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше значение = выше в списке', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Для иерархии тематик (например: Физика -> Ядерная физика)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conferences.topic', verbose_name='Родительская тематика')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(help_text='Выберите тематики конференции (можно несколько)', related_name='conferences', to='conferences.topic', verbose_name='Научные направления'),
        ),
        migrations.CreateModel(
            name='ConferenceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=255, verbose_name='Место работы/учебы')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('presentation_title', models.CharField(max_length=500, verbose_name='Тема доклада')),
                ('presentation_type', models.CharField(choices=[('plenary', 'Пленарный'), ('section', 'Секционный'), ('poster', 'Стендовый'), ('workshop', 'Мастер-класс'), ('listener', 'Слушатель (без доклада)')], default='section', max_length=50, verbose_name='Тип доклада')),
                ('abstract', models.FileField(blank=True, null=True, upload_to='applications/abstracts/', verbose_name='Файл с тезисами')),
                ('abstract_text', models.TextField(blank=True, help_text='Можно вставить текст тезисов, если нет файла', verbose_name='Текст тезисов')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация для оргкомитета', verbose_name='Комментарий к заявке')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('waitlist', 'Лист ожидания'), ('payment', 'Ожидает оплаты'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('organizer_comment', models.TextField(blank=True, help_text='Внутренний комментарий оргкомитета', verbose_name='Комментарий организатора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='conferences.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на участие',
                'verbose_name_plural': 'Заявки на участие',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='conferences_status_958a01_idx'), models.Index(fields=['conference', 'status'], name='conferences_confere_1d579b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConferenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], verbose_name='Оценка')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pros', models.TextField(blank=True, verbose_name='Что понравилось')),
                ('cons', models.TextField(blank=True, verbose_name='Что можно улучшить')),
                ('is_verified', models.BooleanField(default=False, help_text='Пользователь действительно участвовал в конференции', verbose_name='Подтвержденный участник')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conferences.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='conferences.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная конференция',
                'verbose_name_plural': 'Избранные конференции',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранная организация',
                'verbose_name_plural': 'Избранные организации',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['status', 'start_date'], name='conferences_status_6904fa_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['-start_date'], name='conferences_start_d_9269b1_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['deadline'], name='conferences_deadlin_e55ade_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['conference_type'], name='conferences_confere_2a58e0_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['format'], name='conferences_format_7cb7b3_idx'),
        ),
    ]
