# Generated by Django 6.0.2 on 2026-02-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('waitlist', 'Лист ожидания'), ('payment', 'Ожидает оплаты'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
