# Generated by Django 6.0.2 on 2026-03-19 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferenceapplication_status'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start_date', 'title'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='conferencefile',
            options={'verbose_name': 'Файл мероприятия', 'verbose_name_plural': 'Файлы мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='favoriteconference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное мероприятие', 'verbose_name_plural': 'Избранные мероприятия'},
        ),
        migrations.RemoveIndex(
            model_name='conference',
            name='conferences_confere_2a58e0_idx',
        ),
        migrations.AddField(
            model_name='conference',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Конференция'), ('forum', 'Форум'), ('seminar', 'Семинар'), ('round_table', 'Круглый стол'), ('symposium', 'Симпозиум'), ('congress', 'Конгресс'), ('school', 'Школа-конференция'), ('workshop', 'Мастер-класс')], default='conference', max_length=20, verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='conference',
            name='online_meeting_link',
            field=models.URLField(blank=True, help_text='Ссылка на Яндекс Телемост или другую платформу (будет отправлена участникам)', verbose_name='Ссылка на онлайн-встречу'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participation_format',
            field=models.CharField(choices=[('offline', 'Очно'), ('online', 'Дистанционно'), ('hybrid', 'Гибридно (можно выбрать при подаче)')], default='hybrid', help_text='Выберите, какие форматы участия доступны', max_length=20, verbose_name='Доступные форматы участия'),
        ),
        migrations.AddField(
            model_name='conference',
            name='requirements_file',
            field=models.FileField(blank=True, help_text='Загрузите файл с требованиями (PDF, DOC, DOCX)', null=True, upload_to='conferences/requirements/', verbose_name='Файл с требованиями'),
        ),
        migrations.AddField(
            model_name='conference',
            name='requirements_link',
            field=models.URLField(blank=True, help_text='Ссылка на страницу с требованиями на вашем сайте', verbose_name='Ссылка на требования'),
        ),
        migrations.AddField(
            model_name='conferenceapplication',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Ссылка для дистанционных участников', verbose_name='Ссылка на онлайн-встречу'),
        ),
        migrations.AddField(
            model_name='conferenceapplication',
            name='participation_format',
            field=models.CharField(choices=[('offline', 'Очно'), ('online', 'Дистанционно')], default='offline', help_text='Выберите предпочтительный формат участия', max_length=20, verbose_name='Формат участия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(help_text='Подробное описание, цели, задачи', verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(help_text='Дата окончания мероприятия', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать на главной в блоке "Рекомендуемые"', verbose_name='Рекомендуемое'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Участие бесплатное?', verbose_name='Бесплатное'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='online_platform',
            field=models.CharField(blank=True, help_text='Например: Zoom, Webinar, Яндекс Телемост', max_length=200, verbose_name='Платформа для онлайн-участия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='organization',
            field=models.ForeignKey(help_text='Организация, проводящая мероприятие', on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='organizations.organization', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='poster',
            field=models.ImageField(blank=True, help_text='Изображение для привлечения внимания', null=True, upload_to='conferences/posters/', verbose_name='Постер мероприятия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.TextField(blank=True, help_text='Программа мероприятия, пленарные докладчики', verbose_name='Программа мероприятия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_title',
            field=models.CharField(blank=True, help_text='Аббревиатура или краткая форма (например: "ICM-2026")', max_length=100, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(help_text='Дата начала мероприятия', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('archived', 'В архиве'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(help_text='Полное официальное название', max_length=300, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='topics',
            field=models.ManyToManyField(help_text='Выберите тематики мероприятия (можно несколько)', related_name='conferences', to='conferences.topic', verbose_name='Научные направления'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='website',
            field=models.URLField(blank=True, help_text='Официальный сайт, если есть отдельный', verbose_name='Сайт мероприятия'),
        ),
        migrations.AlterField(
            model_name='conferencereview',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Пользователь действительно участвовал в мероприятии', verbose_name='Подтвержденный участник'),
        ),
        migrations.AlterUniqueTogether(
            name='conferenceapplication',
            unique_together={('user', 'conference')},
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['event_type'], name='conferences_event_t_de3650_idx'),
        ),
        migrations.RemoveField(
            model_name='conference',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='conference_type',
        ),
    ]
