# Generated by Django 6.0.2 on 2026-02-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное официальное название', max_length=255, verbose_name='Название организации')),
                ('short_name', models.CharField(blank=True, help_text='Например: МГУ, НИЯУ МИФИ, ИППИ РАН', max_length=100, verbose_name='Краткое название')),
                ('inn', models.CharField(help_text='Идентификационный номер налогоплательщика', max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Код причины постановки на учет (для юрлиц)', max_length=9, verbose_name='КПП')),
                ('legal_address', models.TextField(help_text='Официальный юридический адрес', verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, help_text='Если отличается от юридического', verbose_name='Фактический адрес')),
                ('contact_person', models.CharField(help_text='ФИО ответственного за конференции', max_length=255, verbose_name='Контактное лицо')),
                ('contact_position', models.CharField(blank=True, help_text='Например: начальник отдела аспирантуры', max_length=200, verbose_name='Должность контактного лица')),
                ('contact_email', models.EmailField(help_text='На этот email будут приходить уведомления', max_length=254, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(help_text='Контактный телефон с кодом города', max_length=20, verbose_name='Телефон')),
                ('contact_fax', models.CharField(blank=True, max_length=20, verbose_name='Факс')),
                ('website', models.URLField(blank=True, help_text='Официальный сайт', verbose_name='Сайт организации')),
                ('logo', models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x200px', null=True, upload_to='organizations/logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, help_text='Краткая информация о деятельности, достижениях', verbose_name='Описание организации')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('is_active', models.BooleanField(default=False, help_text='Организация может создавать конференции только при активном договоре', verbose_name='Договор активен')),
                ('is_verified', models.BooleanField(default=False, help_text='Официально подтверждено, что организация реальна', verbose_name='Верифицирована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Аккаунт для входа в личный кабинет организации', on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Представитель организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='organizations/documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('certificate', 'Свидетельство'), ('other', 'Другое')], default='contract', max_length=50, verbose_name='Тип документа')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Документ организации',
                'verbose_name_plural': 'Документы организаций',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['inn'], name='organizatio_inn_dc47b1_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx'),
        ),
    ]
