# Generated by Django 6.0.2 on 2026-02-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчёта')),
                ('report_type', models.CharField(choices=[('conferences', 'Отчёт по конференциям'), ('applications', 'Отчёт по заявкам'), ('organizations', 'Отчёт по организациям'), ('users', 'Отчёт по пользователям'), ('custom', 'Пользовательский отчёт')], max_length=20, verbose_name='Тип отчёта')),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10, verbose_name='Формат')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчёта')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('completed', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчёта')),
                ('report_type', models.CharField(choices=[('conferences', 'Отчёт по конференциям'), ('applications', 'Отчёт по заявкам'), ('organizations', 'Отчёт по организациям'), ('users', 'Отчёт по пользователям'), ('custom', 'Пользовательский отчёт')], max_length=20, verbose_name='Тип отчёта')),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10, verbose_name='Формат')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально')], max_length=20, verbose_name='Периодичность')),
                ('recipients', models.TextField(help_text='Email адреса через запятую', verbose_name='Получатели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('next_run', models.DateTimeField(verbose_name='Следующий запуск')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запланированный отчёт',
                'verbose_name_plural': 'Запланированные отчёты',
            },
        ),
    ]
