# Generated by Django 6.0.2 on 2026-03-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_invitation',
            field=models.BooleanField(default=True, verbose_name='Приглашения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deadline', 'Приближение дедлайна'), ('application', 'Изменение статуса заявки'), ('new_conf', 'Новое мероприятие по интересам'), ('fav_org', 'Новости от избранной организации'), ('reminder', 'Напоминание о мероприятии'), ('invitation', 'Приглашение к участию'), ('meeting_link', 'Ссылка на онлайн-встречу'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_new_conference',
            field=models.BooleanField(default=True, verbose_name='Новые мероприятия'),
        ),
    ]
